/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author oslop8441
 */
public class QQ extends javax.swing.JFrame {

    /**
     * Creates new form panelQQ
     */
    public QQ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelQQ = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblFirstQuestion = new javax.swing.JLabel();
        txtUserAnswer1 = new javax.swing.JTextField();
        lblSecondQuestion = new javax.swing.JLabel();
        txtUserAnswer2 = new javax.swing.JTextField();
        lblThirdQuestion = new javax.swing.JLabel();
        txtUserAnswer3 = new javax.swing.JTextField();
        lblFourthQuestion = new javax.swing.JLabel();
        txtUserAnswer4 = new javax.swing.JTextField();
        lblFifthQuestion = new javax.swing.JLabel();
        txtUserAnswer5 = new javax.swing.JTextField();
        bttnCheckAnswers = new javax.swing.JButton();
        lblQuote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setText("Positivism");

        lblFirstQuestion.setText("Are you feeling lonely?");

        lblSecondQuestion.setText("Are you feeling sad?");

        lblThirdQuestion.setText("Are you feeling depressed?");

        lblFourthQuestion.setText("Are you hurt?");

        lblFifthQuestion.setText("Are you feeling angry?");

        bttnCheckAnswers.setText("Check Answers");
        bttnCheckAnswers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCheckAnswersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQQLayout = new javax.swing.GroupLayout(panelQQ);
        panelQQ.setLayout(panelQQLayout);
        panelQQLayout.setHorizontalGroup(
            panelQQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQQLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstQuestion)
                    .addComponent(lblSecondQuestion)
                    .addComponent(lblThirdQuestion)
                    .addComponent(lblFourthQuestion)
                    .addComponent(lblFifthQuestion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelQQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtUserAnswer5, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(txtUserAnswer4)
                    .addComponent(txtUserAnswer3)
                    .addComponent(txtUserAnswer2)
                    .addComponent(txtUserAnswer1))
                .addGap(70, 70, 70))
            .addGroup(panelQQLayout.createSequentialGroup()
                .addGroup(panelQQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQQLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(bttnCheckAnswers))
                    .addGroup(panelQQLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQuote))
                    .addGroup(panelQQLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(lblHeader)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        panelQQLayout.setVerticalGroup(
            panelQQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQQLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelQQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstQuestion)
                    .addComponent(txtUserAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelQQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSecondQuestion)
                    .addComponent(txtUserAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelQQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThirdQuestion)
                    .addComponent(txtUserAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelQQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFourthQuestion)
                    .addComponent(txtUserAnswer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelQQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFifthQuestion)
                    .addComponent(txtUserAnswer5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(bttnCheckAnswers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQuote)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelQQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelQQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnCheckAnswersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCheckAnswersActionPerformed
        //varaiable declaration area
        String userAnswer1 = "";
        String userAnswer2 = "";
        String userAnswer3 = "";
        String userAnswer4 = "";
        String userAnswer5 = "";
        
        // get the information from the text field for the first answer
        userAnswer1 = txtUserAnswer1.getText();
        // get the information from the text field for the second answer
        userAnswer2 = txtUserAnswer2.getText();
        // get the information from the text field for the third answer
        userAnswer3 = txtUserAnswer3.getText();
        // get the information from the text field for the fourth answer
        userAnswer4 = txtUserAnswer4.getText();
        // get the information from the text field for the fifth answer
        userAnswer5 = txtUserAnswer5.getText();
        
        //possible outputs
        if (userAnswer1.equals("Yes")||userAnswer2.equals("No")||userAnswer3.equals("No")||userAnswer4.equals("No")||userAnswer5.equals("No")) {
            lblQuote.setText("How beautiful it is to find someone who asks for nothing but your company.");
        }
        else if  (userAnswer1.equals("No")||userAnswer2.equals("Yes")||userAnswer3.equals("No")||userAnswer4.equals("No")||userAnswer5.equals("No")) {
            lblQuote.setText("We are all in the gutter, but some of us are looking at the stars.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("No")||userAnswer3.equals("Yes")||userAnswer4.equals("No")||userAnswer5.equals("No")) {
            lblQuote.setText("Never regret a day in your life. Good days give you happines & bad days give you experience.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("No")||userAnswer3.equals("No")||userAnswer4.equals("Yes")||userAnswer5.equals("No")) {
            lblQuote.setText("Happiness is not by chance, but by choice.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("No")||userAnswer3.equals("No")||userAnswer4.equals("No")||userAnswer5.equals("Yes")) {
            lblQuote.setText("They laugh at me because I'm different, I laugh at them because they're all the same.");
        }
        else if (userAnswer1.equals("Yes")||userAnswer2.equals("Yes")||userAnswer3.equals("No")||userAnswer4.equals("No")||userAnswer5.equals("No")) {
            lblQuote.setText("Not until we are lost do we begin to understand ourselves.");
        }
        else if (userAnswer1.equals("Yes")||userAnswer2.equals("Yes")||userAnswer3.equals("Yes")||userAnswer4.equals("No")||userAnswer5.equals("No")) {
            lblQuote.setText("Life is weird. First you wanna grow up, then you wanna be a kid again.");
        }
        else if (userAnswer1.equals("Yes")||userAnswer2.equals("Yes")||userAnswer3.equals("Yes")||userAnswer4.equals("Yes")||userAnswer5.equals("No")) {
            lblQuote.setText("I do not at all understand the mistery of grace-only that it meets us where we are but does not leave us where it found us.");
        }
        else if (userAnswer1.equals("Yes")||userAnswer2.equals("Yes")||userAnswer3.equals("Yes")||userAnswer4.equals("Yes")||userAnswer5.equals("Yes")) {
            lblQuote.setText("You are never unwanted. There will always be someone that wants you, and thinks that you're the most extraordinary human being on th planet. Always remember that.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("Yes")||userAnswer3.equals("Yes")||userAnswer4.equals("Yes")||userAnswer5.equals("Yes")) {
            lblQuote.setText("Make your life a masterpiece; imagine npo limitations on what you can be, have or do.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("No")||userAnswer3.equals("Yes")||userAnswer4.equals("Yes")||userAnswer5.equals("Yes")) {
            lblQuote.setText("Overcoming self-limiting beliefs and self-imposed limitations is often the biggest obstacle standing between you and the reslization of your full potential.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("No")||userAnswer3.equals("No")||userAnswer4.equals("Yes")||userAnswer5.equals("Yes")) {
            lblQuote.setText("Accept your past without regret, handle your present with confidence and face your future without fear.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("No")||userAnswer3.equals("No")||userAnswer4.equals("No")||userAnswer5.equals("Yes")) {
            lblQuote.setText("They laugh at me because I'm different, I laugh at them because they're all the same.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("No")||userAnswer3.equals("No")||userAnswer4.equals("No")||userAnswer5.equals("No")) {
            lblQuote.setText("Sometimes you will never know the value of a moment until it becomes a memory.");
        }
        else if (userAnswer1.equals("Yes")||userAnswer2.equals("No")||userAnswer3.equals("Yes")||userAnswer4.equals("No")||userAnswer5.equals("No")) {
            lblQuote.setText("Don't be pushed around by the fears in your mind. Be led by the dreams in  your heart.");
        }
        else if (userAnswer1.equals("Yes")||userAnswer2.equals("No")||userAnswer3.equals("No")||userAnswer4.equals("Yes")||userAnswer5.equals("No")) {
            lblQuote.setText("It's not the load that breaks you down, it's the way you carry it.");
        }
        else if (userAnswer1.equals("Yes")||userAnswer2.equals("No")||userAnswer3.equals("No")||userAnswer4.equals("No")||userAnswer5.equals("Yes")) {
            lblQuote.setText("The older I get, the more I understand that it's ok to live a life others don't understand.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("Yes")||userAnswer3.equals("No")||userAnswer4.equals("No")||userAnswer5.equals("Yes")) {
            lblQuote.setText("Work hard in silence, let success be your noise.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("Yes")||userAnswer3.equals("No")||userAnswer4.equals("Yes")||userAnswer5.equals("Yes")) {
            lblQuote.setText("Don't talk, just act. Don't say, just show. Don't promise, just prove.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("Yes")||userAnswer3.equals("Yes")||userAnswer4.equals("No")||userAnswer5.equals("No")) {
            lblQuote.setText("Happines can be found even in the darkest of times when one only remembers to turn on the light.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("Yes")||userAnswer3.equals("Yes")||userAnswer4.equals("Yes")||userAnswer5.equals("No")) {
            lblQuote.setText("Every adversity, every failure and every heartache carries with it the seed of an equivalent or greater benefit.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("Yes")||userAnswer3.equals("No")||userAnswer4.equals("Yes")||userAnswer5.equals("No")) {
            lblQuote.setText("When you have a dream, you've got to grab it and never let go.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("No")||userAnswer3.equals("Yes")||userAnswer4.equals("Yes")||userAnswer5.equals("No")) {
            lblQuote.setText("If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do... keep moving forward.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("No")||userAnswer3.equals("Yes")||userAnswer4.equals("Yes")||userAnswer5.equals("Yes")) {
            lblQuote.setText("Success is not final, failure is not fatal: it is the courage to continue that counts.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("Yes")||userAnswer3.equals("No")||userAnswer4.equals("Yes")||userAnswer5.equals("Yes")) {
            lblQuote.setText("Don't talk, just act. Don't say, just show. Don't promise, just prove.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("No")||userAnswer3.equals("Yes")||userAnswer4.equals("No")||userAnswer5.equals("Yes")) {
            lblQuote.setText("Nothing is permanent in this wicked world, not even our troubles.");
        }
        else if (userAnswer1.equals("Yes")||userAnswer2.equals("Yes")||userAnswer3.equals("No")||userAnswer4.equals("Yes")||userAnswer5.equals("No")) {
            lblQuote.setText("The goal is to laugh forever with someone you take seriously.");
        }
        else if (userAnswer1.equals("Yes")||userAnswer2.equals("No")||userAnswer3.equals("Yes")||userAnswer4.equals("Yes")||userAnswer5.equals("No")) {
            lblQuote.setText("Silence says a lot more than you think.");
        }
        else if (userAnswer1.equals("No")||userAnswer2.equals("Yes")||userAnswer3.equals("Yes")||userAnswer4.equals("No")||userAnswer5.equals("Yes")) {
            lblQuote.setText("The most wasted of days is one without laughter.");
        }
        else if (userAnswer1.equals("Yes")||userAnswer2.equals("No")||userAnswer3.equals("Yes")||userAnswer4.equals("No")||userAnswer5.equals("Yes")) {
            lblQuote.setText("You can't go back and change the beginning, but you can start where you are and change the ending.");
        }
        else if (userAnswer1.equals("Yes")||userAnswer2.equals("No")||userAnswer3.equals("No")||userAnswer4.equals("Yes")||userAnswer5.equals("Yes")) {
            lblQuote.setText("You do not find the happy life. You make it.");
        }
        else if (userAnswer1.equals("Yes")||userAnswer2.equals("Yes")||userAnswer3.equals("No")||userAnswer4.equals("No")||userAnswer5.equals("Yes")) {
            lblQuote.setText("Act as if what you do makes a difference. It does.");
        }
        else
            {lblQuote.setText("Invalid Response");}
    }//GEN-LAST:event_bttnCheckAnswersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QQ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCheckAnswers;
    private javax.swing.JLabel lblFifthQuestion;
    private javax.swing.JLabel lblFirstQuestion;
    private javax.swing.JLabel lblFourthQuestion;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblQuote;
    private javax.swing.JLabel lblSecondQuestion;
    private javax.swing.JLabel lblThirdQuestion;
    private javax.swing.JPanel panelQQ;
    private javax.swing.JTextField txtUserAnswer1;
    private javax.swing.JTextField txtUserAnswer2;
    private javax.swing.JTextField txtUserAnswer3;
    private javax.swing.JTextField txtUserAnswer4;
    private javax.swing.JTextField txtUserAnswer5;
    // End of variables declaration//GEN-END:variables
}
